# Eoloplanner K8s workloads


# Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      securityContext:
        runAsUser: 1000
      restartPolicy: Always
      containers:
      - name: server
        image: oscarsotosanchez/server:v1.0
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DB
          value: eoloplantsDB
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASS
          value: password
        - name: RABBITMQ_URL
          value: amqp://root:password@rabbitmq
---

# Weatherservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice
spec:
  selector:
    matchLabels:
      app: weatherservice
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      securityContext:
        runAsUser: 1000
      restartPolicy: Always
      containers:
      - name: weatherservice
        image: oscarsotosanchez/weatherservice:v1.0
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: GRPC_HOST
          value: 0.0.0.0
        - name: GRPC_PORT
          value: "9090"         
---

# Planner
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner
spec:
  selector:
    matchLabels:
      app: planner
  replicas: 1
  template:
    metadata:
      labels:
        app: planner
    spec:
      securityContext:
        runAsUser: 1000
      restartPolicy: Always
      containers:
      - name: planner
        image: oscarsotosanchez/planner:v1.0
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: TOPO_HOST
          value: toposervice
        - name: TOPO_PORT
          value: "8080"
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://weatherservice:9090
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
---


# Toposervice 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toposervice
spec:
  selector:
    matchLabels:
      app: toposervice
  replicas: 1
  template:
    metadata:
      labels:
        app: toposervice
    spec:
      securityContext:
        runAsUser: 1000
      restartPolicy: Always
      containers:
      - name: toposervice
        image: oscarsotosanchez/toposervice:v1.0
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: topoDB
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_USERNAME
          value: root
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        - name: SERVER_PORT
          value: "8080"
---

# MySQL 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: eoloplantsDB
        - name: MYSQL_ROOT_PASSWORD
          value: password
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
---

# Mongo DB
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:4.2.12-bionic
        env:
        - name: MONGO_INITDB_DATABASE
          value: topoDB
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
---

# RabbitMQ
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: password
        volumeMounts:
          - name: rabbit-volume
            mountPath: /var/lib/rabbitmq/mnesia
      volumes:
        - name: rabbit-volume
          persistentVolumeClaim:
            claimName: rabbit-pvc
---
