package es.codeurjc.orderservice.types;

public enum OrderEventEnum {
	ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_FAILED, DELIVER_ORDER, DELIVERY_SUCCESS, DELIVERY_FAILED, RESERVE_CREDIT, CREDIT_APPROVED, CREDIT_REJECTED
   
}
